### ISSUE TITLE
[Tagger] Tagger still references "./src/input/" even if I change IMAGE_TAGGER_INPUT_DIR option in config.py.

### ISSUE THREAD

**Issue by Shimo-Neko** [Inupedia/sd-character-image-preprocessing#1]
When I use --tag argument, I change the IMAGE_TAGGER_INPUT_DIR option in config.py, but the option does not working and still references "./src/input/";

This problem was probably caused by "for filename in os.listdir(image_directory)" on line 31 of "module\image_tagger\image_tagger.py".

https://github.com/Inupedia/anime-character-image-preprocessing/blob/983f03b8395863a43ba29224501f100eaaca94e5/module/image_tagger/image_tagger.py#L31

I suggest changing this code as follows.
```python
                for filename in os.listdir(self.image_directory)
```

**Comment by Inupedia** [comment]
Yep, you're right. It suppose be for filename in os.listdir(self.image_directory) instead.
